/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Ownable } from "./Ownable";
export type { ERC20 } from "./ERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { Distribute } from "./Distribute";
export type { Holder } from "./Holder";
export type { SimpleToken } from "./SimpleToken";

export { Ownable__factory } from "./factories/Ownable__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { Distribute__factory } from "./factories/Distribute__factory";
export { Holder__factory } from "./factories/Holder__factory";
export { SimpleToken__factory } from "./factories/SimpleToken__factory";
