const NETWORK_NAME_MAINNET = "mainnet";
const NETWORK_NAME_MATIC = "matic";
const NETWORK_NAME_RINKEBY = "rinkeby";
const NETWORK_NAME_GETH_LOCALHOST = "geth_localhost";
const ENV_PREFIX_REACT_APP = "REACT_APP";
const ENV_ERC20_CONTRACT_ADDRESS = "ERC20_CONTRACT_ADDRESS";
const ENV_DISTRIBUTER_CONTRACT_ADDRESS = "DISTRIBUTER_CONTRACT_ADDRESS";

export {
    ENV_PREFIX_REACT_APP,
    ENV_ERC20_CONTRACT_ADDRESS,
    ENV_DISTRIBUTER_CONTRACT_ADDRESS,
    NETWORK_NAME_MAINNET,
    NETWORK_NAME_MATIC,
    NETWORK_NAME_RINKEBY,
    NETWORK_NAME_GETH_LOCALHOST,
};