import { NETWORK_NAMES, CHAIN_IDS } from "./CustomInputs";

const ENV_PREFIX_REACT_APP = "REACT_APP";
const ENV_ERC20_CONTRACT_ADDRESS = "ERC20_CONTRACT_ADDRESS";
const ENV_DISTRIBUTER_CONTRACT_ADDRESS = "DISTRIBUTER_CONTRACT_ADDRESS";

export {
    ENV_PREFIX_REACT_APP,
    ENV_ERC20_CONTRACT_ADDRESS,
    ENV_DISTRIBUTER_CONTRACT_ADDRESS,
    NETWORK_NAMES,
    CHAIN_IDS,
};